default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.49.11
    hooks:
      - id: swiftformat
  - repo: https://github.com/realm/SwiftLint
    rev: 0.47.1
    hooks:
      - id: swiftlint
  - repo: local
    hooks:
      - id: tuist-generate
        always_run: true
        entry: make tuist_generate
        language: system
        name: tuist-generate
        pass_filenames: false
        stages: [post-checkout]
